trigger:
  - main

pr:
  - main

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: dev
  values:
    - dev
    - prod
variables:
- group: aws-credentials

jobs:
- job: Terraform_Plan
  displayName: 'Terraform Plan'
  pool:
    name: aws-agent

  steps:
  - checkout: self
    persistCredentials: true


  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

 
  - script: |
      git clone https://github.com/shrookmuhamed/Terraform_project.git
      cd Terraform_project/day1  # Adjust this path according to your repository structure
    displayName: 'Clone Terraform repository'

  - script: terraform init
    displayName: 'Terraform Init'  
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: us-east-1

  - script: |
      terraform workspace select ${{ parameters.ENV }} || terraform workspace new ${{ parameters.ENV }}
    displayName: 'Select or Create Terraform Workspace and init'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: us-east-1

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: us-east-1

