
trigger:
- main

pr:
  - main

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: dev
  values:
  - dev
  - prod
jobs:
- job: Terraform_Init
  displayName: 'Terraform Init'
  pool:
    name: aws-agent

  steps:
  - checkout: self
    persistCredentials: true
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - script: |
      git clone https://github.com/shrookmuhamed/Terraform_project.git
      cd Terraform_project/day1 
    displayName: 'Clone Terraform repository'

  - script: terraform init
    displayName: 'Terraform Init'
    workingDirectory: terraform-repo

- job: Terraform_Plan
  displayName: 'Terraform Plan'
  dependsOn: Terraform_Init
  pool:
    name: aws-agent
  steps:
  - checkout: self
    persistCredentials: true
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
 
  - script: |
      git clone https://github.com/shrookmuhamed/Terraform_project.git
      cd Terraform_project/day1 
    displayName: 'Clone Terraform repository'
  - script: |
      terraform workspace select ${{ parameters.ENV }} || terraform workspace new ${{ parameters.ENV }}
    displayName: 'Select or Create Terraform Workspace'

  - script: terraform plan -out=tfplan
    displayName: 'Terraform Plan'
   
