#Second pipeline,CD depends on CI 
trigger:
  - main
pr:
  - main

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: dev
  values:
    - dev
    - prod
  
- name: ACTION
  displayName: 'Action'
  type: string
  default: 'destroy'
  values:
    - 'apply'
    - 'destroy'

variables:
- group: aws-credentials

jobs:
- job: Terraform_Plan
  displayName: 'Terraform Plan'
  pool:
    name: aws-agent

  steps:
  - checkout: self
    persistCredentials: true


  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

 
  - script: |
      git clone https://github.com/shrookmuhamed/Terraform_project.git
      cd Terraform_project/day1 
      terraform init
      terraform workspace select ${{ parameters.ENV }} || terraform workspace new ${{ parameters.ENV }}
      terraform plan --var-file ${{ parameters.ENV }}.tfvars
    displayName: 'init/Select or Create Terraform Workspace/plan '
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: us-east-1



- job: Terraform_Apply_Destroy
  displayName: 'Terraform Apply or Destroy'
  dependsOn: Terraform_Plan
  pool:
    name: aws-agent

  steps:
    - checkout: self
      persistCredentials: true

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: |
          git clone https://github.com/shrookmuhamed/Terraform_project.git
          cd Terraform_project/day1 
          terraform init
          terraform workspace select ${{ parameters.ENV }} || terraform workspace new ${{ parameters.ENV }}
          if [ "${{ parameters.ACTION }}" == "apply" ]; then
            terraform apply -auto-approve --var-file ${{ parameters.ENV }}.tfvars
          elif [ "${{ parameters.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve --var-file ${{ parameters.ENV }}.tfvars
          else
            echo "Invalid ACTION parameter specified."
            exit 1
          fi
      displayName: 'Terraform Apply or Destroy'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: 'us-east-1' 
