trigger:
  - main

pr:
  - main

parameters:
- name: ENV
  displayName: ENV
  type: string
  default: dev
  values:
    - dev
    - prod

variables:
  AWS_SERVICE_CONNECTION: 'aws'  

jobs:
- job: Terraform_Init
  displayName: 'Terraform Init'
  pool:
    name: aws-agent

  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      sudo apt-get update
      sudo apt-get install -y unzip
    displayName: 'Install unzip'

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - script: |
      git clone https://github.com/shrookmuhamed/Terraform_project.git
      cd Terraform_project/day1  
    displayName: 'Clone Terraform repository'

  - script: |
      echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID]$(<aws-access-key-id>)"
      echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY]$(<aws-secret-access-key>)"
      echo "##vso[task.setvariable variable=AWS_DEFAULT_REGION]us-east-1"
    displayName: 'Set AWS Credentials'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - script: terraform init
    displayName: 'Terraform Init'

- job: Terraform_Plan
  displayName: 'Terraform Plan'
  dependsOn: Terraform_Init
  pool:
    name: aws-agent

  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      sudo apt-get update
      sudo apt-get install -y unzip
    displayName: 'Install unzip'

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - script: |
      git clone https://github.com/shrookmuhamed/Terraform_project.git
      cd Terraform_project/day1  
    displayName: 'Clone Terraform repository'

  - script: |
      echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID]$(<aws-access-key-id>)"
      echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY]$(<aws-secret-access-key>)"
      echo "##vso[task.setvariable variable=AWS_DEFAULT_REGION]us-east-1"
    displayName: 'Set AWS Credentials'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - script: |
      terraform workspace select ${{ parameters.ENV }} || terraform workspace new ${{ parameters.ENV }}
    displayName: 'Select or Create Terraform Workspace'

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'
