
trigger:
- main

pr:
  - main

jobs:
- job: Terraform_Init
  displayName: 'Terraform Init'
  pool:
    name: aws-agent

  steps:
  - checkout: self
    persistCredentials: true
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - script: |
      git clone https://github.com/shrookmuhamed/azure-devops/tree/main.git
      cd azure-devops
    displayName: 'Clone Terraform repository'

  - script: terraform init
    displayName: 'Terraform Init'
    workingDirectory: terraform-repo

- job: Terraform_Plan
  displayName: 'Terraform Plan'
  dependsOn: Terraform_Init
  pool:
    name: aws-agent
  steps:
  - checkout: self
    persistCredentials: true
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
 
  - script: |
      git clone https://github.com/shrookmuhamed/azure-devops/tree/main.git
      cd azure-devops
    displayName: 'Clone Terraform repository'

  - script: terraform plan -out=tfplan
    displayName: 'Terraform Plan'
   
